# Generated by Django 5.0.3 on 2024-03-27 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Kategoriyalar"},
        ),
    ]
