# Generated by Django 5.0.3 on 2024-04-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0002_alter_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("mobile", models.CharField(max_length=50)),
                ("address", models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
    ]
