# Generated by Django 5.0.3 on 2024-04-01 11:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0002_alter_product_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="product",
            table=None,
        ),
    ]
