# Generated by Django 5.0.3 on 2024-04-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0003_order_transaction_rename_name_product_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
