# Generated by Django 5.0.6 on 2024-05-29 12:36

import apps.models.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0003_user_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminUserProxy",
            fields=[],
            options={
                "verbose_name": "Admin",
                "verbose_name_plural": "Admins",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps.user",),
            managers=[
                ("objects", apps.models.managers.AdminManager()),
            ],
        ),
        migrations.CreateModel(
            name="ModeratorUserProxy",
            fields=[],
            options={
                "verbose_name": "Moderator",
                "verbose_name_plural": "Moderators",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps.user",),
            managers=[
                ("objects", apps.models.managers.ModeratorManager()),
            ],
        ),
        migrations.CreateModel(
            name="StudentUserProxy",
            fields=[],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps.user",),
            managers=[
                ("objects", apps.models.managers.StudentManager()),
            ],
        ),
        migrations.CreateModel(
            name="TeacherUserProxy",
            fields=[],
            options={
                "verbose_name": "Teacher",
                "verbose_name_plural": "Teachers",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("apps.user",),
            managers=[
                ("objects", apps.models.managers.TeacherManager()),
            ],
        ),
        migrations.RenameField(
            model_name="course",
            old_name="users",
            new_name="students",
        ),
    ]
