# Generated by Django 5.0.3 on 2024-05-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0003_category_tag_blog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("image", models.ImageField(upload_to="products/%Y/%m")),
                ("description", models.TextField(blank=True, null=True)),
                ("info", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
