# Generated by Django 5.0.3 on 2024-03-27 11:20

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0003_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
