# Generated by Django 5.0.3 on 2024-05-01 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0004_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="info",
        ),
    ]
