# Generated by Django 5.0.6 on 2024-05-29 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0004_adminuserproxy_moderatoruserproxy_studentuserproxy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type": "student"},
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
