# Generated by Django 5.0.3 on 2024-04-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0004_post_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("profession", models.CharField(max_length=255)),
                ("photo", models.ImageField(upload_to="advisors/%Y/%m/%d/")),
            ],
        ),
        migrations.RemoveField(
            model_name="comment",
            name="post",
        ),
        migrations.RemoveField(
            model_name="post",
            name="user",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
