# Generated by Django 5.0.3 on 2024-04-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0005_blog_tag_remove_post_author_delete_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="tag",
            field=models.ManyToManyField(blank=True, to="apps.tag"),
        ),
    ]
