# Generated by Django 5.0.3 on 2024-05-01 16:04

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0005_remove_product_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="info",
            field=django.contrib.postgres.fields.hstore.HStoreField(
                blank=True, null=True
            ),
        ),
    ]
