# Generated by Django 5.0.3 on 2024-05-01 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0006_product_info"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="info",
        ),
    ]
