# Generated by Django 5.0.3 on 2024-04-17 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0006_tag_delete_transaction_product_tags"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="product",
            table=None,
        ),
    ]
