# Generated by Django 5.0.3 on 2024-03-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0006_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(null=True, upload_to="products/"),
        ),
    ]
