# Generated by Django 5.0.3 on 2024-04-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0007_alter_product_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
